holamundo/holamundo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ticketsoporte.urls")), 
]

holamundo/ticketsoporte/urls.py
from django.urls import path
from .views import cliente_form, dispositivo_form, incidencia_form, buscar_incidencia, gestion_clientes, actualizar_estado

urlpatterns = [
    path('cliente/', cliente_form, name='cliente_form'),
    path('dispositivo/<int:cliente_id>/', dispositivo_form, name='dispositivo_form'),
    path('incidencia/<int:cliente_id>/<int:dispositivo_id>/', incidencia_form, name='incidencia_form'),
    path('', buscar_incidencia, name='buscar_incidencia'),
    
    #lista incidencias
    path('gestion_clientes/', gestion_clientes, name='gestion_clientes'),
    path('actualizar_estado/<int:incidencia_id>/', actualizar_estado, name='actualizar_estado'),
]

holamundo/ticketsoporte/models.py
from django.db import models

class Cliente(models.Model):
    identificacion = models.CharField(max_length=13)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    ciudad = models.CharField(max_length=50)
    tipocliente = models.CharField(max_length=10, choices=[('hogar', 'Hogar'), ('empresa', 'Empresa')])
    def __str__(self):
        return self.nombre

class Dispositivo(models.Model):
    tipo = models.CharField(max_length=20, choices=[('portatil', 'Portátil'), ('pc_escritorio', 'PC de escritorio'), ('impresora', 'Impresora'), ('componente', 'Componente'), ('otros', 'Otros')])
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    serie = models.CharField(max_length=50)
    observacion = models.TextField()
    #cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)

class Incidencia(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    dispositivo = models.ForeignKey(Dispositivo, on_delete=models.CASCADE, null=True, blank=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    descripcion_corta = models.CharField(max_length=100)
    estado_fisico = models.CharField(max_length=80)
    componente_adjunto = models.TextField()
    tipo_servicio = models.CharField(max_length=10, choices=[('remoto', 'Remoto'), ('taller', 'Taller'), ('insitu', 'In Situ')])
    estado = models.CharField(max_length=30, default='no_iniciado', null=True, blank=True, choices=[('no_iniciado', 'No Iniciado'), ('en_proceso', 'En Proceso'), ('confirmacion', 'Esperando Confirmación del Cliente'), ('aprobado_por_cliente', 'Aprobado por el Cliente'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')])
    costo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    resultado_incidencia = models.TextField(null=True, blank=True)
    sugerencias = models.TextField(null=True, blank=True)

holamundo/ticketsoporte/forms.py
from django import forms
from .models import Cliente, Dispositivo, Incidencia

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

class DispositivoForm(forms.ModelForm):
    class Meta:
        model = Dispositivo
        fields = '__all__'
        widgets = {
            'cliente': forms.HiddenInput(),  # Este widget ocultará el campo en el formulario HTML
        }
        def __init__(self, *args, **kwargs):
            super(DispositivoForm, self).__init__(*args, **kwargs)
            self.fields['cliente'].required = False

class IncidenciaForm(forms.ModelForm):
    class Meta:
        model = Incidencia
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(IncidenciaForm, self).__init__(*args, **kwargs)
        self.fields['cliente'].widget.attrs['disabled'] = 'disabled'
        self.fields['dispositivo'].widget.attrs['disabled'] = 'disabled'
        self.fields['estado'].widget.attrs['disabled'] = 'disabled'
        self.fields['costo'].widget = forms.HiddenInput()
        self.fields['resultado_incidencia'].widget = forms.HiddenInput()
        self.fields['sugerencias'].widget = forms.HiddenInput()





class BusquedaIncidenciaForm(forms.Form):
    incidencia_id = forms.IntegerField(label='ID de Incidencia', min_value=1)



#lista incidencias
class ActualizarEstadoForm(forms.ModelForm):
    class Meta:
        model = Incidencia
        fields = ['estado', 'descripcion_corta', 'estado_fisico', 'costo', 'resultado_incidencia', 'sugerencias']

holamundo/ticketsoporte/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ClienteForm, DispositivoForm, IncidenciaForm, Cliente, Dispositivo


def cliente_form(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save()
            # Redirigir a la vista para crear un dispositivo, pasando el ID del cliente
            return redirect('dispositivo_form', cliente_id=cliente.id)
    else:
        form = ClienteForm()

    return render(request, 'cliente_form.html', {'form': form})

def dispositivo_form(request, cliente_id):
    cliente = Cliente.objects.get(id=cliente_id)

    if request.method == 'POST':
        form = DispositivoForm(request.POST)
        if form.is_valid():
            dispositivo = form.save(commit=False)
            dispositivo.cliente = cliente
            dispositivo.save()
            # Redirigir a la vista para crear una incidencia, pasando el ID del cliente y del dispositivo
            return redirect('incidencia_form', cliente_id=cliente.id, dispositivo_id=dispositivo.id)
    else:
        form = DispositivoForm()

    return render(request, 'dispositivo_form.html', {'form': form, 'cliente': cliente})

def incidencia_form(request, cliente_id, dispositivo_id):
    cliente = Cliente.objects.get(id=cliente_id)
    dispositivo = Dispositivo.objects.get(id=dispositivo_id)

    if request.method == 'POST':
        form = IncidenciaForm(request.POST)
        if form.is_valid():
            incidencia = form.save(commit=False)
            incidencia.cliente = cliente
            incidencia.dispositivo = dispositivo
            incidencia.save()
            # Redirigir a la página de formulario completado u otro destino
            return redirect('cliente_form')
    else:
        form = IncidenciaForm(initial={'cliente': cliente.id, 'dispositivo': dispositivo.id})
        #form = IncidenciaForm()

    return render(request, 'incidencia_form.html', {'form': form, 'cliente': cliente, 'dispositivo': dispositivo})




""" from django.core.mail import send_mail
from django.template.loader import render_to_string

def enviar_correo(cliente, dispositivo, incidencia):
    subject = 'Formulario Completado'
    message = render_to_string('correo_template.txt', {'cliente': cliente, 'dispositivo': dispositivo, 'incidencia': incidencia})
    from_email = 'tu@email.com'
    to_email = [cliente.email]  # Asegúrate de que el modelo Cliente tenga un campo 'email'

    send_mail(subject, message, from_email, to_email) """

# ...
from .models import Incidencia
from .forms import BusquedaIncidenciaForm
from django.http import Http404, HttpResponse

def buscar_incidencia(request):
    incidencia = None

    if request.method == 'POST':
        form = BusquedaIncidenciaForm(request.POST)
        if form.is_valid():
            incidencia_id = form.cleaned_data['incidencia_id']
            try:
                incidencia = Incidencia.objects.get(id=incidencia_id)
            except Incidencia.DoesNotExist:
                raise Http404("La incidencia no existe.")
    else:
        form = BusquedaIncidenciaForm()

    return render(request, 'buscar_incidencia.html', {'form': form, 'incidencia': incidencia})


    

#vista de incidencias
def gestion_clientes(request):
    incidencias = Incidencia.objects.all()
    return render(request, 'gestion_clientes.html', {'incidencias': incidencias})

from .forms import ActualizarEstadoForm

def actualizar_estado(request, incidencia_id):
    incidencia = get_object_or_404(Incidencia, id=incidencia_id)

    if request.method == 'POST':
        form = ActualizarEstadoForm(request.POST, instance=incidencia)
        if form.is_valid():
            form.save()
            return redirect('gestion_clientes')
    else:
        form = ActualizarEstadoForm(instance=incidencia)

    return render(request, 'actualizar_estado.html', {'form': form})

holamundo/ticketsoporte/templates/actualizar_estado.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Actualizar estado</title>
</head>
<body>
  
</body>
</html>

{% block content %}
  <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="30%" />
  <h2>Actualizar Estado de Incidencia</h2>

  <form method="post" action="">
    {% csrf_token %}
    {{ form.estado.label_tag }} {{ form.estado }}
    {{ form.descripcion_corta.label_tag }} {{ form.descripcion_corta }}
    {{ form.estado_fisico.label_tag }} {{ form.estado_fisico }}
    {{ form.costo.label_tag }} {{ form.costo }}
    {{ form.resultado_incidencia.label_tag }} {{ form.resultado_incidencia }}
    {{ form.sugerencias.label_tag }} {{ form.sugerencias }}
    <input type="submit" value="Actualizar">
  </form>

  <br>
  <a href="{% url 'gestion_clientes' %}">Volver al Listado de Incidencias</a>
  <br><br>
  <p>_</p>
{% endblock %}

holamundo/ticketsoporte/templates/buscar_incidencia.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Inicio</title>
</head>
<body>

    
    <br>
    <form method="post" action="{% url 'buscar_incidencia' %}">
        <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="60%" />
        <h3>Busqueda de Ticket de soporte técnico</h3>

        <br>

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Buscar</button>
    </form>
    
    {% if incidencia %}
    <section >
        <aside>    
            <strong>ID:</strong> {{ incidencia.id }}<br>
            <strong>Cliente:</strong> {{ incidencia.cliente.nombre }}<br>
            <strong>Dispositivo:</strong> {{ incidencia.dispositivo.get_tipo_display }}<br>
            <strong>Descripción Corta:</strong> {{ incidencia.descripcion_corta }}<br>
            <strong>Estado:</strong> {{ incidencia.get_estado_display }}<br>
            {% if incidencia.costo is not None %}
                <strong>Costo:</strong> {{ incidencia.costo }}<br>                
            {% endif %}

            {% if incidencia.resultado_incidencia is not None %}
                <strong>Resultado Incidencia:</strong> {{ incidencia.resultado_incidencia }}<br>
            {% endif %}
            {% if incidencia.sugerencias is not None %}
                <strong>Sugerencias:</strong> {{ incidencia.sugerencias }}<br>
            {% endif %}
        </aside>
    </section>
    {% else %}
    <p>{{ incidencia }}</p> {# Muestra un mensaje personalizado cuando la incidencia no existe #}
    {% endif %}

    <br><br>
    <h3><a href="{% url 'cliente_form' %}">Registrar un Ticket de Soporte técnico</a></h3>
    <h4><a href="{% url 'gestion_clientes' %}">Gestión de Clientes</a></h4>
</body>
</html>

holamundo/ticketsoporte/templates/cliente_form.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Datos del Cliente</title>
</head>
<body>
  
  <form method="post" action="{% url 'cliente_form' %}">
      <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="70%" />
      <h3>Registro de Datos de Cliente</h3>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Siguiente">
    </form>

    <br><br>
    <h3><a href="{% url 'buscar_incidencia' %}">Regresar al Inicio</a></h3>
    <br><br>
    <p>_</p>
</body>
</html>

holamundo/ticketsoporte/templates/dispositivo_form.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Datos del Dispositivo</title>
</head>
<body>
  
  <form method="post" action="{% url 'dispositivo_form' cliente.id %}">
      <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="70%" />
      <h3>Registro de Datos del Dispositivo</h3>
      {% csrf_token %}
      <input type="hidden" name="cliente_id" value="{{ id_cliente }}">
      {{ form.as_p }}
      <input type="submit" value="Siguiente">
  </form>
  
</body>
</html>

holamundo/ticketsoporte/templates/gestion_clientes.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Gestión de Clientes</title>
</head>
<body>
  
  {% block content %}

  <section >
    <aside style="width: 85%">
      <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="30%" />

      <h2>Listado de Incidencias</h2>
    
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Dispositivo</th>
            <th>Fecha de Registro</th>
            <th>Descripción Corta</th>
            <th>Estado Físico</th>
            <th>Estado</th>
            <th>Actualizar Estado</th>
          </tr>
        </thead>
        <tbody>
          {% for incidencia in incidencias %}
            <tr>
              <td>{{ incidencia.id }}</td>
              <td>{{ incidencia.cliente.nombre }}</td>
              <td>{{ incidencia.dispositivo }}</td>
              <td>{{ incidencia.fecha_registro }}</td>
              <td>{{ incidencia.descripcion_corta }}</td>
              <td>{{ incidencia.estado_fisico }}</td>
              <td>{{ incidencia.get_estado_display }}</td>
              <td><a href="{% url 'actualizar_estado' incidencia.id %}">Actualizar Estado</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </aside>
  </section>
  {% endblock %}
  <h3><a href="{% url 'buscar_incidencia' %}">Regresar al Inicio</a></h3>
  <br><br>
  <p>_</p>
</body>
</html>

holamundo/ticketsoporte/templates/incidencia_form.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://unpkg.com/mvp.css"> 
  <title>Datos de la Incidencia</title>
</head>
<body>
  
  <form method="post" action="{% url 'incidencia_form' cliente.id dispositivo.id %}">
      <img src="https://live.staticflickr.com/5723/22919843673_622c53e3ae_b.jpg" alt="" width="70%" />
      <h3>Registro de Incidencia</h3>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Finalizar">
  </form>
  
</body>
</html>